// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeniorCareManager.WebAPI.Data;

#nullable disable

namespace SeniorCareManager.WebAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809013824_AddSessionAndMfa")]
    partial class AddSessionAndMfa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.AccessPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Effect")
                        .HasColumnType("integer")
                        .HasColumnName("effect");

                    b.Property<string>("Feature")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<Guid>("PolicyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_key");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_key");

                    b.Property<int?>("ScopeType")
                        .HasColumnType("integer")
                        .HasColumnName("scope_type");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PolicyKey", "Version")
                        .IsUnique();

                    b.HasIndex("InstitutionId", "Resource", "Action", "Feature", "State");

                    b.ToTable("accesspolicy");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("accounttoken");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AccountState")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("IdentityOrigin")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("InstitutionId", "NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("InstitutionId", "NormalizedUserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressComplement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("addresscomplement");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("corporatename");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpfcnpj");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postalcode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tradename");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("carrier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressComplement = "Próximo ao banco",
                            City = "São Paulo",
                            CorporateName = "Transportes ABC LTDA",
                            CpfCnpj = "12345678000190",
                            District = "Centro",
                            Email = "contato@abctransportes.com",
                            Number = "123",
                            Phone = "11987654321",
                            PostalCode = "01001000",
                            State = "SP",
                            Street = "Rua das Flores",
                            TradeName = "ABC Transportes"
                        },
                        new
                        {
                            Id = 2,
                            AddressComplement = "Esquina com a Rua Augusta",
                            City = "São Paulo",
                            CorporateName = "Expresso XYZ S/A",
                            CpfCnpj = "98765432000180",
                            District = "Bela Vista",
                            Email = "expresso@xyz.com.br",
                            Number = "456",
                            Phone = "11976543210",
                            PostalCode = "01311000",
                            State = "SP",
                            Street = "Avenida Paulista",
                            TradeName = "Expresso XYZ"
                        },
                        new
                        {
                            Id = 3,
                            AddressComplement = "Próximo ao metrô",
                            City = "Rio de Janeiro",
                            CorporateName = "Translogística EFG ME",
                            CpfCnpj = "22334455000122",
                            District = "Centro",
                            Email = "contato@efgtrans.com.br",
                            Number = "789",
                            Phone = "21987654321",
                            PostalCode = "20040001",
                            State = "RJ",
                            Street = "Avenida Rio Branco",
                            TradeName = "EFG Transportes"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.HealthInsurancePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("healthinsuranceplan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "UNI",
                            Name = "Unimed",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "HAP",
                            Name = "Hapvida",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "SUS",
                            Name = "Sistema Único de Saúde",
                            Type = 1
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AccessTokenDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("access_token_duration_minutes");

                    b.Property<int?>("LockoutDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("lockout_duration_minutes");

                    b.Property<int?>("MaxFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_failed_attempts");

                    b.Property<bool>("MfaRequiredForAllUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_required_for_all_users");

                    b.Property<int?>("MinPasswordLengthWithMfaOverride")
                        .HasColumnType("integer")
                        .HasColumnName("min_password_length_with_mfa_override");

                    b.Property<int?>("MinPasswordLengthWithoutMfaOverride")
                        .HasColumnType("integer")
                        .HasColumnName("min_password_length_without_mfa_override");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("RefreshTokenDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_token_duration_days");

                    b.HasKey("Id");

                    b.ToTable("institution");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("corporate_name");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tradename");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorporateName = "Empresa A",
                            CpfCnpj = "12345678000195",
                            Email = "contato@empresaa.com",
                            Phone = "12345678901",
                            TradeName = "Trade A"
                        },
                        new
                        {
                            Id = 2,
                            CorporateName = "Empresa B",
                            CpfCnpj = "12345678000196",
                            Email = "contato@empresab.com",
                            Phone = "23456789012",
                            TradeName = "Trade B"
                        },
                        new
                        {
                            Id = 3,
                            CorporateName = "Empresa C",
                            CpfCnpj = "12345678000197",
                            Email = "contato@empresac.com",
                            Phone = "34567890123",
                            TradeName = "Trade C"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Name")
                        .IsUnique();

                    b.ToTable("organizationalrole");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationalRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_role_id");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_key");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalRoleId");

                    b.HasIndex("UserId", "OrganizationalRoleId", "ValidFrom");

                    b.ToTable("organizationalroleassignment");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRolePermissionGroup", b =>
                {
                    b.Property<Guid>("OrganizationalRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_role_id");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.HasKey("OrganizationalRoleId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("organizationalrolepermissiongroup");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Feature")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature");

                    b.Property<bool>("IsSystemOperation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_operation");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action", "Feature")
                        .IsUnique();

                    b.ToTable("permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4822d058-ab3c-4233-9d72-2e06515cf06a"),
                            Action = "read",
                            Description = "Consultar ProductGroup",
                            IsSystemOperation = false,
                            Resource = "ProductGroup"
                        },
                        new
                        {
                            Id = new Guid("3b31d0c5-b52c-43a0-a638-959df4e76e9b"),
                            Action = "write",
                            Description = "Criar ou editar ProductGroup",
                            IsSystemOperation = false,
                            Resource = "ProductGroup"
                        },
                        new
                        {
                            Id = new Guid("28913e62-e1c2-4e04-8559-202c895507db"),
                            Action = "delete",
                            Description = "Excluir/inativar ProductGroup",
                            IsSystemOperation = false,
                            Resource = "ProductGroup"
                        },
                        new
                        {
                            Id = new Guid("1d065485-c1f5-4e68-af1b-97aae10d837d"),
                            Action = "read",
                            Description = "Consultar ProductType",
                            IsSystemOperation = false,
                            Resource = "ProductType"
                        },
                        new
                        {
                            Id = new Guid("3dc837df-49d2-4e29-bc50-9b83c211569c"),
                            Action = "write",
                            Description = "Criar ou editar ProductType",
                            IsSystemOperation = false,
                            Resource = "ProductType"
                        },
                        new
                        {
                            Id = new Guid("111491e2-dfe4-44ba-a791-70ea17930a56"),
                            Action = "delete",
                            Description = "Excluir/inativar ProductType",
                            IsSystemOperation = false,
                            Resource = "ProductType"
                        },
                        new
                        {
                            Id = new Guid("c479d380-4550-4c6f-acde-30ba2ad0123e"),
                            Action = "read",
                            Description = "Consultar Supplier",
                            IsSystemOperation = false,
                            Resource = "Supplier"
                        },
                        new
                        {
                            Id = new Guid("80d2bc17-66d5-4f08-a7a0-7123b0556db7"),
                            Action = "write",
                            Description = "Criar ou editar Supplier",
                            IsSystemOperation = false,
                            Resource = "Supplier"
                        },
                        new
                        {
                            Id = new Guid("d099399d-f909-4346-b649-1c45d22ae870"),
                            Action = "delete",
                            Description = "Excluir/inativar Supplier",
                            IsSystemOperation = false,
                            Resource = "Supplier"
                        },
                        new
                        {
                            Id = new Guid("bf087d0a-1912-4839-962f-784e232319ab"),
                            Action = "read",
                            Description = "Consultar UnitOfMeasure",
                            IsSystemOperation = false,
                            Resource = "UnitOfMeasure"
                        },
                        new
                        {
                            Id = new Guid("d1e9b982-cc0f-4194-8d95-09db6cf51bd6"),
                            Action = "write",
                            Description = "Criar ou editar UnitOfMeasure",
                            IsSystemOperation = false,
                            Resource = "UnitOfMeasure"
                        },
                        new
                        {
                            Id = new Guid("89eb36b4-f5ff-4ddf-9cc2-875f4ff80f9e"),
                            Action = "delete",
                            Description = "Excluir/inativar UnitOfMeasure",
                            IsSystemOperation = false,
                            Resource = "UnitOfMeasure"
                        },
                        new
                        {
                            Id = new Guid("bdffd7c8-9ce2-4faa-86ac-939116ac0e87"),
                            Action = "read",
                            Description = "Consultar Manufacturer",
                            IsSystemOperation = false,
                            Resource = "Manufacturer"
                        },
                        new
                        {
                            Id = new Guid("5d767431-4c88-4a96-a7af-5b27338c4078"),
                            Action = "write",
                            Description = "Criar ou editar Manufacturer",
                            IsSystemOperation = false,
                            Resource = "Manufacturer"
                        },
                        new
                        {
                            Id = new Guid("325e6bf1-7d8d-4faf-ab66-216b6ff53012"),
                            Action = "delete",
                            Description = "Excluir/inativar Manufacturer",
                            IsSystemOperation = false,
                            Resource = "Manufacturer"
                        },
                        new
                        {
                            Id = new Guid("27725187-00d6-47ab-a39e-9bfddcf7a039"),
                            Action = "read",
                            Description = "Consultar Carrier",
                            IsSystemOperation = false,
                            Resource = "Carrier"
                        },
                        new
                        {
                            Id = new Guid("1b0ebb43-0aa5-449a-9246-d25290c80bc2"),
                            Action = "write",
                            Description = "Criar ou editar Carrier",
                            IsSystemOperation = false,
                            Resource = "Carrier"
                        },
                        new
                        {
                            Id = new Guid("e8e754a2-4cb9-461f-a773-3ce9adbb4ecb"),
                            Action = "delete",
                            Description = "Excluir/inativar Carrier",
                            IsSystemOperation = false,
                            Resource = "Carrier"
                        },
                        new
                        {
                            Id = new Guid("b9efb981-e8e0-4d44-a45f-89ef7218fa34"),
                            Action = "read",
                            Description = "Consultar HealthInsurancePlan",
                            IsSystemOperation = false,
                            Resource = "HealthInsurancePlan"
                        },
                        new
                        {
                            Id = new Guid("91ede0cb-5492-4e1f-a5aa-67edd6eeb231"),
                            Action = "write",
                            Description = "Criar ou editar HealthInsurancePlan",
                            IsSystemOperation = false,
                            Resource = "HealthInsurancePlan"
                        },
                        new
                        {
                            Id = new Guid("12512f07-e33c-4e91-bb92-5b2b22e389e6"),
                            Action = "delete",
                            Description = "Excluir/inativar HealthInsurancePlan",
                            IsSystemOperation = false,
                            Resource = "HealthInsurancePlan"
                        },
                        new
                        {
                            Id = new Guid("8e6d9b0d-2adb-48da-a8bf-63c6fc775ddc"),
                            Action = "read",
                            Description = "Consultar Position",
                            IsSystemOperation = false,
                            Resource = "Position"
                        },
                        new
                        {
                            Id = new Guid("ab0a7b57-9d6d-4110-85e7-c001f16072fc"),
                            Action = "write",
                            Description = "Criar ou editar Position",
                            IsSystemOperation = false,
                            Resource = "Position"
                        },
                        new
                        {
                            Id = new Guid("91cd749c-2d6e-453f-8d94-991f7f422300"),
                            Action = "delete",
                            Description = "Excluir/inativar Position",
                            IsSystemOperation = false,
                            Resource = "Position"
                        },
                        new
                        {
                            Id = new Guid("2be2a833-9f65-4cdc-a721-c54aa6c1a606"),
                            Action = "read",
                            Description = "Consultar Religion",
                            IsSystemOperation = false,
                            Resource = "Religion"
                        },
                        new
                        {
                            Id = new Guid("fc15ca1c-1a6c-4451-926d-d4e746862b93"),
                            Action = "write",
                            Description = "Criar ou editar Religion",
                            IsSystemOperation = false,
                            Resource = "Religion"
                        },
                        new
                        {
                            Id = new Guid("f7a4145c-e73e-4297-ba84-acb35d392478"),
                            Action = "delete",
                            Description = "Excluir/inativar Religion",
                            IsSystemOperation = false,
                            Resource = "Religion"
                        },
                        new
                        {
                            Id = new Guid("188d0a43-405d-4c12-b520-8c4c8f770552"),
                            Action = "read",
                            Description = "Consultar contas administradas",
                            IsSystemOperation = false,
                            Resource = "AdminUser"
                        },
                        new
                        {
                            Id = new Guid("f6e45a8b-b685-4115-ab83-50d7bd72c787"),
                            Action = "write",
                            Description = "Criar contas e alterar seu estado",
                            IsSystemOperation = false,
                            Resource = "AdminUser"
                        },
                        new
                        {
                            Id = new Guid("5190a83c-a319-4b8d-bb49-d9a758f03c39"),
                            Action = "read",
                            Description = "Consultar papéis técnicos",
                            IsSystemOperation = false,
                            Resource = "Role"
                        },
                        new
                        {
                            Id = new Guid("bdcb5194-b695-4ed9-b575-c5f5f3b1304e"),
                            Action = "write",
                            Description = "Criar ou editar papéis técnicos",
                            IsSystemOperation = false,
                            Resource = "Role"
                        },
                        new
                        {
                            Id = new Guid("aec7d56c-388a-40cc-8302-31e03b336773"),
                            Action = "delete",
                            Description = "Excluir papéis técnicos",
                            IsSystemOperation = false,
                            Resource = "Role"
                        },
                        new
                        {
                            Id = new Guid("74cd4700-c774-4f08-b525-824397055d0e"),
                            Action = "read",
                            Description = "Consultar grupos de permissão",
                            IsSystemOperation = false,
                            Resource = "PermissionGroup"
                        },
                        new
                        {
                            Id = new Guid("c95b0ca8-63e9-4363-b440-a7b8525bf6e4"),
                            Action = "write",
                            Description = "Criar ou editar grupos de permissão",
                            IsSystemOperation = false,
                            Resource = "PermissionGroup"
                        },
                        new
                        {
                            Id = new Guid("a5d9432f-b6e2-44a1-8a4a-0736fee1b740"),
                            Action = "delete",
                            Description = "Excluir grupos de permissão",
                            IsSystemOperation = false,
                            Resource = "PermissionGroup"
                        },
                        new
                        {
                            Id = new Guid("16e1a13e-4fce-4b23-adfc-d3cbe098d3d2"),
                            Action = "read",
                            Description = "Consultar o catálogo de permissões",
                            IsSystemOperation = false,
                            Resource = "Permission"
                        },
                        new
                        {
                            Id = new Guid("7ce48309-c3f1-4826-8fac-890d425ba9f0"),
                            Action = "read",
                            Description = "Consultar responsabilidades organizacionais",
                            IsSystemOperation = false,
                            Resource = "OrganizationalRole"
                        },
                        new
                        {
                            Id = new Guid("467dcc23-d406-4af0-8110-e35054d2b0a7"),
                            Action = "write",
                            Description = "Criar ou editar responsabilidades organizacionais",
                            IsSystemOperation = false,
                            Resource = "OrganizationalRole"
                        },
                        new
                        {
                            Id = new Guid("27b676e3-c59f-496a-accc-e2e6a85a5b37"),
                            Action = "delete",
                            Description = "Excluir responsabilidades organizacionais",
                            IsSystemOperation = false,
                            Resource = "OrganizationalRole"
                        },
                        new
                        {
                            Id = new Guid("20eff295-7744-4a5e-86e1-383185bd7dd8"),
                            Action = "read",
                            Description = "Consultar atribuições de responsabilidade",
                            IsSystemOperation = false,
                            Resource = "OrganizationalRoleAssignment"
                        },
                        new
                        {
                            Id = new Guid("339fa802-d1b2-4b92-9737-78695f2dc0b9"),
                            Action = "write",
                            Description = "Criar ou encerrar atribuições de responsabilidade",
                            IsSystemOperation = false,
                            Resource = "OrganizationalRoleAssignment"
                        },
                        new
                        {
                            Id = new Guid("e1bacfeb-75a4-48e1-beed-66a6fa0a68a5"),
                            Action = "read",
                            Description = "Consultar exceções individuais",
                            IsSystemOperation = false,
                            Resource = "UserPermissionOverride"
                        },
                        new
                        {
                            Id = new Guid("1a5beb30-0976-46ae-8b8a-43b74c869675"),
                            Action = "write",
                            Description = "Criar ou revogar exceções individuais",
                            IsSystemOperation = false,
                            Resource = "UserPermissionOverride"
                        },
                        new
                        {
                            Id = new Guid("16402be8-d47d-4394-a6d5-1f0f48c6a1b5"),
                            Action = "read",
                            Description = "Consultar políticas condicionais",
                            IsSystemOperation = false,
                            Resource = "AccessPolicy"
                        },
                        new
                        {
                            Id = new Guid("f4c0a499-dcb4-47fb-9928-7be9e2dfe385"),
                            Action = "write",
                            Description = "Criar novas versões de política condicional",
                            IsSystemOperation = false,
                            Resource = "AccessPolicy"
                        },
                        new
                        {
                            Id = new Guid("4acd0f81-38b7-44a3-b082-1eabfc938272"),
                            Action = "read",
                            Description = "Consultar parâmetros de segurança institucionais",
                            IsSystemOperation = false,
                            Resource = "InstitutionSecurityPolicy"
                        },
                        new
                        {
                            Id = new Guid("1f5c759b-2c24-41c5-aaaa-d011a45d6e26"),
                            Action = "write",
                            Description = "Alterar parâmetros de segurança institucionais",
                            IsSystemOperation = false,
                            Resource = "InstitutionSecurityPolicy"
                        },
                        new
                        {
                            Id = new Guid("ba85fad3-3ca2-4c97-9c6e-47473e6dd9f4"),
                            Action = "read",
                            Description = "Consultar sessões ativas",
                            IsSystemOperation = false,
                            Resource = "UserSession"
                        },
                        new
                        {
                            Id = new Guid("93c69a5f-c382-40f8-8e94-c56c7c890721"),
                            Action = "write",
                            Description = "Revogar sessões ativas",
                            IsSystemOperation = false,
                            Resource = "UserSession"
                        },
                        new
                        {
                            Id = new Guid("02ceffd4-f764-4916-94a3-5a45db960bf2"),
                            Action = "read",
                            Description = "Explicar uma decisão de acesso para suporte/auditoria",
                            IsSystemOperation = false,
                            Resource = "AccessDecisionExplanation"
                        },
                        new
                        {
                            Id = new Guid("21344fa6-54a6-4dc9-9696-eee38bc42680"),
                            Action = "manage",
                            Description = "Marca a identidade como administradora de acesso institucional",
                            IsSystemOperation = false,
                            Resource = "AccessAdministration"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("permissiongroup");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.PermissionGroupPermission", b =>
                {
                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("PermissionGroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("permissiongrouppermission");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Enfermeiros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cuidadores"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cozinheiro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nutricionista"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("productgroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medicamentos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Equipamentos Médicos"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suplementos"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("productgroupid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("producttype");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Legumes",
                            ProductGroupId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carnes",
                            ProductGroupId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Frutas",
                            ProductGroupId = 3
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("religion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Católico"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Evangelico"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ateu"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Name")
                        .IsUnique();

                    b.ToTable("role");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.RolePermissionGroup", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_group_id");

                    b.HasKey("RoleId", "PermissionGroupId");

                    b.HasIndex("PermissionGroupId");

                    b.ToTable("rolepermissiongroup");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressComplement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_complement");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("corporate_name");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trade_name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("unitofmeasure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "kg",
                            Description = "Kilogram"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "m",
                            Description = "Meter"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "l",
                            Description = "Liter"
                        });
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Effect")
                        .HasColumnType("integer")
                        .HasColumnName("effect");

                    b.Property<string>("Feature")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justification");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_key");

                    b.Property<int?>("ScopeType")
                        .HasColumnType("integer")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Resource", "Action", "Feature");

                    b.ToTable("userpermissionoverride");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("userrole");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentKeyHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("current_key_hash");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastRotatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("PreviousKeyHash")
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)")
                        .HasColumnName("previous_key_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("usersession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRoleAssignment", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRole", null)
                        .WithMany()
                        .HasForeignKey("OrganizationalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRolePermissionGroup", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.OrganizationalRole", null)
                        .WithMany()
                        .HasForeignKey("OrganizationalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.PermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.PermissionGroupPermission", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.PermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.ProductType", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ProductGroup", "ProductGroup")
                        .WithMany("ProductType")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.RolePermissionGroup", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.PermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserPermissionOverride", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserRole", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.UserSession", b =>
                {
                    b.HasOne("SeniorCareManager.WebAPI.Objects.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeniorCareManager.WebAPI.Objects.Models.ProductGroup", b =>
                {
                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
